#!/usr/bin/env python
#

import zmq
import time
import commands
import argparse

context = zmq.Context()
zmq_socket = context.socket(zmq.PUSH)
zmq_socket.connect("ipc:///tmp/motors.ipc")


def move_ass(direction, duration, speed)

   if direction=='f':
      r_sign = 1
	  l_sign = 1
   elif direction=='b'
      r_sign = -1
	  l_sign = -1
   elif direction=='l'
      r_sign = 1
	  l_sign = -1
   elif direction=='r'
      r_sign = -1
      l_sign = 1
   
   if duration > 5:
       duration = 5
   
   lval = l_sign * speed
   rval = r_sign * speed
   msg = {'leftA': '1000', 'rightA': '1000', 'leftV': lval, 'rightV': rval}
   print "moving " + direction + "for " + str(duration) + "s"
   zmq_socket.send_json(msg)
   time.sleep(duration)
   msg = {'leftA': '300', 'rightA': '300', 'leftV': '0', 'rightV': '0'}
   zmq_socket.send_json(msg)
   print "stopped."
   
if __name__ == "__main__":
   parser = argparse.ArgumentParser(description='Moved the ass-bot\'s ass.')
   parser.add_argument('direction', help='move forward (f), back (b), left (l) or right(r)')
   parser.add_argument('duration', type=int, help='move duration in seconds')
   parser.add_argument('speed', type=int, help='speed percent of max speed (0-100)')
   args = parser.parse_args()
   print args   
   move_ass(args.direction,args.duration,args.speed)