#!/bin/sh

### BEGIN INIT INFO
# Provides:             phidgetwebservice
# Required-Start:       $network $remote_fs
# Required-Stop:        $network $remote_fs
# Should-Start:         avahi
# Should-Stop:          avahi
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Phidget Webservice
# Description:          Phidget Webservice for controlling Phidgets over the network
### END INIT INFO

DESC="Phidget Webservice"
NAME=phidgetwebservice
BIN=phidgetwebservice21
DAEMON=/usr/bin/$BIN
PIDFILE=/var/run/$NAME.pid
CFG=/etc/default/$NAME

# Gracefully exit if the package has been removed
test -x $DAEMON || exit 0

# Load config
pws_port="5001"
pws_serverid=""
pws_password=""
[ -f $CFG ] && . $CFG

start() {
        [ -z "$pws_port" ] || OPTIONS="-p $pws_port "
        [ -z "$pws_password" ] || OPTIONS="$OPTIONS-P $pws_password "

        if [ -z "$pws_serverid" ]; then
                OPTIONS="$OPTIONS -n $( hostname )"
        else
                OPTIONS="$OPTIONS -n $pws_serverid"
        fi

        echo -n "Starting $DESC: "
        start-stop-daemon -S -b -q -p $PIDFILE -m -x $DAEMON -- $OPTIONS && echo "OK..." || echo "ALREADY RUNNING..."
}

stop() {
        echo -n "Stopping $DESC: "
        start-stop-daemon -K -q -p $PIDFILE -x $DAEMON && echo "OK..." || echo "NOT RUNNING..."
}

status() {
        if (( $(ps -ef | grep -v grep | grep $BIN | wc -l) > 0 ))
        then
                echo -n "$DESC: is Running..."
        else
                echo -n "$DESC: is Not Running..."
        fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart|force-reload)
        stop
        sleep 1
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"

esac

exit 0
